# ----
# Site

title: God's Fingers
url: "https://godsfingers.kr"
baseurl:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description:
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name:
  links:

# -----
# Build

markdown: kramdown
timezone: "Asia/Seoul"
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor
  - vendor/bundle/

collections:
  staff_members:
    _hide_content: true

paginate: 5
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['category']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
        content:
          width: 1500
          height: 2000
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
